### ISSUE TITLE
关于Exoplayer

### ISSUE THREAD

**Issue by yangwuan55** [duanyao/web-developer-note#1]
hi 我看到您在Exoplayer的关于改变视频播放速度的提交，我尝试用您的代码，但发现声音速度并没有发生改变。想请教一下您，声音目前是改变不了，还是要用其他解决办法？期待您的回答，多谢。

**Comment by duanyao** [comment]
要改变声音速度，目前需要运行在 android 6.0 (API 23) 及以上的设备，我在那个提交中已经提到了。这是个废弃的仓库，我可能注意不到你的问题。如果还有问题，可以到那个PR下面去讨论 :)

**Comment by yangwuan55** [comment]
我已经解决了6.0以下声音变速的问题，感谢你的回答。
